# Generated by Django 3.2 on 2022-05-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False, help_text='Save a post as a draft')),
                ('archived', models.BooleanField(default=False, help_text='You may archive a post instead of deleting it.')),
                ('was_archived', models.BooleanField(default=False, help_text='Post was archived at some point.')),
                ('edited', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('date_published', models.DateTimeField(blank=True, null=True, verbose_name='Published On')),
                ('date_edited', models.DateTimeField(blank=True, null=True, verbose_name='Edited On')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('utd_ratio', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(blank=True, null=True, upload_to='posts_vids')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsvideos', to='pages.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animage', models.ImageField(blank=True, null=True, upload_to='posts_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsimages', to='pages.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afile', models.FileField(blank=True, null=True, upload_to='posts_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsfiles', to='pages.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itscomments', to='pages.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theircomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
